--[[
    ******************************************************************************
    * @name         : omniMarket
    * @authors      : 
    * @date         : 
    * @lastEdit     : 
    * @brief        : 
    * @version      : 1.0.0
    ******************************************************************************
    * @attention
    *
    * Copyright © 2026 Axon Corporation.
    * All rights reserved.
    *
    * This software is licensed under terms that can be found in the LICENSE file
    * in the root directory of this software component.
    * If no LICENSE file comes with this software, it is provided AS-IS.
    *
    ******************************************************************************
--]]

--// Libs
local libs = script.libs

--omniMarket.src.__index.luau
return 
